#!/usr/bin/env python3

import os
import re
import sys
import argparse
import subprocess

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord


# =========================================================
# Arguments
# =========================================================

def parse_arguments():

    parser = argparse.ArgumentParser(
        description=(
            "Add one or more outgroup sequences from MO "
            "ortholog files to corresponding RT alignments, "
            "followed by MAFFT alignment."
        )
    )

    parser.add_argument(
        "OUTGROUP_FILE",
        help="Text file containing outgroup taxon names, one per line"
    )

    parser.add_argument(
        "MO_DIR",
        help="Directory containing MO ortholog FASTA files"
    )

    parser.add_argument(
        "RT_DIR",
        help="Directory containing RT ortholog FASTA files"
    )

    parser.add_argument(
        "OUT_DIR",
        help="Output directory for RT alignments with outgroups"
    )

    parser.add_argument(
        "--mafft",
        default="mafft",
        help="Path to MAFFT executable [default: mafft]"
    )

    return parser.parse_args()


args = parse_arguments()

OUTGROUP_FILE = args.OUTGROUP_FILE
MO_DIR = args.MO_DIR
RT_DIR = args.RT_DIR
OUT_DIR = args.OUT_DIR
MAFFT = args.mafft


# =========================================================
# Check input
# =========================================================

if not os.path.isfile(OUTGROUP_FILE):

    sys.exit(
        f"[ERROR] Outgroup file does not exist: "
        f"{OUTGROUP_FILE}"
    )


if not os.path.isdir(MO_DIR):

    sys.exit(
        f"[ERROR] MO directory does not exist: "
        f"{MO_DIR}"
    )


if not os.path.isdir(RT_DIR):

    sys.exit(
        f"[ERROR] RT directory does not exist: "
        f"{RT_DIR}"
    )


os.makedirs(OUT_DIR, exist_ok=True)


# =========================================================
# Read outgroup list
# =========================================================

print("======================================")
print("STEP 1: Reading outgroup list")
print("======================================")


outgroups = []

with open(
    OUTGROUP_FILE,
    "r"
) as f:

    for line in f:

        line = line.strip()

        # Ignore empty lines
        if not line:
            continue

        # Ignore comments
        if line.startswith("#"):
            continue

        # Allow comma-separated names as well
        # e.g. NH506,NH507,NZY078
        names = [
            x.strip()
            for x in line.split(",")
            if x.strip()
        ]

        for name in names:

            if name not in outgroups:
                outgroups.append(name)


if len(outgroups) == 0:

    sys.exit(
        "[ERROR] No outgroups found in "
        f"{OUTGROUP_FILE}"
    )


print(
    f"Outgroups found: {len(outgroups)}"
)

for outgroup in outgroups:

    print(
        f"    {outgroup}"
    )


# =========================================================
# Helper functions
# =========================================================

def get_og(filename):
    """
    Extract OG ID from filename.

    Example:
        OG0017367_paralogs_all.fasta.ortho.fa

    -> OG0017367
    """

    match = re.match(
        r"^(OG\d+)_",
        filename
    )

    if match:
        return match.group(1)

    return None


def get_fasta_files(directory):

    for filename in sorted(
        os.listdir(directory)
    ):

        if filename.endswith(
            (".fa", ".fasta", ".fas")
        ):

            yield filename


# =========================================================
# STEP 2: Read MO files
# =========================================================

print()
print("======================================")
print("STEP 2: Reading MO files")
print("======================================")


mo_files = {}


for filename in get_fasta_files(MO_DIR):

    og = get_og(filename)

    if og is None:
        continue

    # Only keep MO ortholog files
    if ".ortho.fa" not in filename:
        continue

    mo_files[og] = filename


print(
    f"MO OGs found: {len(mo_files)}"
)


if len(mo_files) == 0:

    sys.exit(
        "[ERROR] No MO ortholog files found."
    )


# =========================================================
# STEP 3: Read RT files
# =========================================================

print()
print("======================================")
print("STEP 3: Reading RT files")
print("======================================")


rt_files = {}


for filename in get_fasta_files(RT_DIR):

    # Do not process files generated by this workflow
    if ".added_outgroup." in filename:
        continue

    og = get_og(filename)

    if og is None:
        continue

    # Expected RT pattern:
    #
    # OGxxxx_paralogs_all.fasta.inclade1.ortho1.tre.fa
    #

    if ".inclade" not in filename:
        continue

    if ".ortho" not in filename:
        continue

    if ".tre." not in filename:
        continue

    if og not in rt_files:
        rt_files[og] = []

    rt_files[og].append(filename)


print(
    f"RT OGs found: {len(rt_files)}"
)


total_rt_files = sum(
    len(x)
    for x in rt_files.values()
)


print(
    f"Total RT files: {total_rt_files}"
)


if total_rt_files == 0:

    sys.exit(
        "[ERROR] No RT files found."
    )


# =========================================================
# STEP 4: Prepare summary
# =========================================================

summary_file = os.path.join(
    OUT_DIR,
    "summary.tsv"
)


summary_rows = []


# =========================================================
# Counters
# =========================================================

n_processed = 0
n_added = 0
n_already_same = 0
n_already_different = 0
n_missing_mo = 0
n_missing_outgroup = 0
n_mafft_failed = 0
n_invalid_rt = 0


# =========================================================
# STEP 5: Process each RT OG
# =========================================================

print()
print("======================================")
print("STEP 5: Processing RT files")
print("======================================")


for og in sorted(rt_files):

    print()
    print("======================================")
    print(f"Processing {og}")
    print("======================================")


    # -----------------------------------------------------
    # Check corresponding MO gene
    # -----------------------------------------------------

    if og not in mo_files:

        print(
            f"[WARNING] No corresponding MO file "
            f"for {og}"
        )

        for rt_filename in sorted(
            rt_files[og]
        ):

            summary_rows.append([
                og,
                "",
                rt_filename,
                "MISSING_MO",
                ""
            ])

        n_missing_mo += len(
            rt_files[og]
        )

        continue


    mo_filename = mo_files[og]

    mo_file = os.path.join(
        MO_DIR,
        mo_filename
    )


    print(
        f"MO: {mo_filename}"
    )


    # =====================================================
    # Read all requested outgroups from MO
    # =====================================================

    mo_sequences = {}

    try:

        for record in SeqIO.parse(
            mo_file,
            "fasta"
        ):

            if record.id in outgroups:

                sequence = (
                    str(record.seq)
                    .replace("-", "")
                )

                mo_sequences[
                    record.id
                ] = sequence

    except Exception as e:

        print(
            f"[ERROR] Cannot read MO file "
            f"{mo_filename}: {e}"
        )

        for rt_filename in sorted(
            rt_files[og]
        ):

            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "MO_READ_ERROR",
                str(e)
            ])

        continue


    # -----------------------------------------------------
    # Check requested outgroups
    # -----------------------------------------------------

    missing_outgroups = [
        x
        for x in outgroups
        if x not in mo_sequences
    ]


    if missing_outgroups:

        print(
            "[WARNING] Outgroups missing from MO:"
        )

        for outgroup in missing_outgroups:

            print(
                f"    {outgroup}"
            )


    available_outgroups = [
        x
        for x in outgroups
        if x in mo_sequences
        and len(mo_sequences[x]) > 0
    ]


    if len(available_outgroups) == 0:

        print(
            "[WARNING] No requested outgroups "
            "were found in this MO file."
        )

        for rt_filename in sorted(
            rt_files[og]
        ):

            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "NO_OUTGROUP_AVAILABLE",
                ",".join(missing_outgroups)
            ])

        n_missing_outgroup += len(
            rt_files[og]
        )

        continue


    print(
        "Available outgroups:"
    )

    for outgroup in available_outgroups:

        print(
            f"    {outgroup}: "
            f"{len(mo_sequences[outgroup])} bp"
        )


    # =====================================================
    # Process each RT file
    # =====================================================

    for rt_filename in sorted(
        rt_files[og]
    ):

        n_processed += 1

        print()
        print(
            f"RT: {rt_filename}"
        )


        rt_file = os.path.join(
            RT_DIR,
            rt_filename
        )


        # -------------------------------------------------
        # Read RT alignment
        # -------------------------------------------------

        try:

            rt_records = list(
                SeqIO.parse(
                    rt_file,
                    "fasta"
                )
            )

        except Exception as e:

            print(
                f"[ERROR] Cannot read RT file: "
                f"{e}"
            )

            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "RT_READ_ERROR",
                str(e)
            ])

            n_invalid_rt += 1

            continue


        if len(rt_records) == 0:

            print(
                "[ERROR] RT file contains "
                "no sequences"
            )

            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "EMPTY_RT",
                ""
            ])

            n_invalid_rt += 1

            continue


        # -------------------------------------------------
        # Existing taxa in RT
        # -------------------------------------------------

        existing_taxa = {
            record.id: str(record.seq)
            for record in rt_records
        }


        # -------------------------------------------------
        # Determine which outgroups need to be added
        # -------------------------------------------------

        records_to_add = []

        already_same = []

        already_different = []


        for outgroup in available_outgroups:

            sequence = mo_sequences[
                outgroup
            ]


            # ---------------------------------------------
            # Outgroup already present
            # ---------------------------------------------

            if outgroup in existing_taxa:

                existing_sequence = (
                    existing_taxa[outgroup]
                    .replace("-", "")
                )


                if existing_sequence == sequence:

                    print(
                        f"[INFO] {outgroup} already "
                        f"present and sequence is "
                        f"identical to MO"
                    )

                    already_same.append(
                        outgroup
                    )

                else:

                    print(
                        f"[WARNING] {outgroup} already "
                        f"exists but sequence differs "
                        f"from MO"
                    )

                    already_different.append(
                        outgroup
                    )

                continue


            # ---------------------------------------------
            # Add outgroup
            # ---------------------------------------------

            print(
                f"[INFO] Adding {outgroup}"
            )


            outgroup_record = SeqRecord(
                Seq(sequence),
                id=outgroup,
                description=""
            )


            records_to_add.append(
                outgroup_record
            )


        # -------------------------------------------------
        # Update counters for already-present outgroups
        # -------------------------------------------------

        if already_same:

            n_already_same += len(
                already_same
            )


        if already_different:

            n_already_different += len(
                already_different
            )


        # -------------------------------------------------
        # Nothing needs to be added
        # -------------------------------------------------

        if len(records_to_add) == 0:

            if already_different:

                status = (
                    "OUTGROUP_ALREADY_PRESENT_DIFFERENT"
                )

            else:

                status = (
                    "ALL_OUTGROUPS_ALREADY_PRESENT"
                )


            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                status,
                (
                    f"same={','.join(already_same)};"
                    f"different={','.join(already_different)}"
                )
            ])

            continue


        # =================================================
        # Add all outgroups
        # =================================================

        combined_records = (
            rt_records
            + records_to_add
        )


        # -------------------------------------------------
        # Temporary input
        # -------------------------------------------------

        temp_file = os.path.join(
            OUT_DIR,
            f"{rt_filename}.added_outgroup.tmp.fa"
        )


        # -------------------------------------------------
        # Final output filename
        # -------------------------------------------------

        if rt_filename.endswith(".fa"):

            output_filename = (
                rt_filename[:-3]
                + ".added_outgroup.fa"
            )

        elif rt_filename.endswith(".fasta"):

            output_filename = (
                rt_filename[:-6]
                + ".added_outgroup.fasta"
            )

        elif rt_filename.endswith(".fas"):

            output_filename = (
                rt_filename[:-4]
                + ".added_outgroup.fas"
            )

        else:

            output_filename = (
                rt_filename
                + ".added_outgroup.fa"
            )


        output_file = os.path.join(
            OUT_DIR,
            output_filename
        )


        # -------------------------------------------------
        # Avoid overwriting existing output
        # -------------------------------------------------

        if os.path.exists(output_file):

            print(
                f"[WARNING] Output already exists: "
                f"{output_filename}"
            )

            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "OUTPUT_ALREADY_EXISTS",
                output_filename
            ])

            continue


        # -------------------------------------------------
        # Write temporary FASTA
        # -------------------------------------------------

        try:

            SeqIO.write(
                combined_records,
                temp_file,
                "fasta"
            )

        except Exception as e:

            print(
                f"[ERROR] Cannot write temporary "
                f"file: {e}"
            )

            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "WRITE_TEMP_FAILED",
                str(e)
            ])

            continue


        # =================================================
        # Run MAFFT
        # =================================================

        print(
            "[INFO] Running MAFFT --auto ..."
        )


        try:

            with open(
                output_file,
                "w"
            ) as outfile:

                result = subprocess.run(
                    [
                        MAFFT,
                        "--auto",
                        temp_file
                    ],
                    stdout=outfile,
                    stderr=subprocess.PIPE,
                    text=True
                )


        except Exception as e:

            print(
                f"[ERROR] Could not execute MAFFT: "
                f"{e}"
            )

            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "MAFFT_EXECUTION_ERROR",
                str(e)
            ])

            n_mafft_failed += 1

            if os.path.exists(
                output_file
            ):
                os.remove(
                    output_file
                )

            if os.path.exists(
                temp_file
            ):
                os.remove(
                    temp_file
                )

            continue


        # -------------------------------------------------
        # Check MAFFT result
        # -------------------------------------------------

        if result.returncode != 0:

            print(
                f"[ERROR] MAFFT failed "
                f"for {rt_filename}"
            )

            print(
                result.stderr
            )

            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "MAFFT_FAILED",
                result.stderr.strip()
            ])

            n_mafft_failed += 1

            if os.path.exists(
                output_file
            ):
                os.remove(
                    output_file
                )

            if os.path.exists(
                temp_file
            ):
                os.remove(
                    temp_file
                )

            continue


        # -------------------------------------------------
        # Check output file
        # -------------------------------------------------

        if (
            not os.path.exists(
                output_file
            )
            or os.path.getsize(
                output_file
            ) == 0
        ):

            print(
                "[ERROR] MAFFT produced "
                "an empty file"
            )

            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "EMPTY_MAFFT_OUTPUT",
                ""
            ])

            n_mafft_failed += 1

            if os.path.exists(
                output_file
            ):
                os.remove(
                    output_file
                )

            if os.path.exists(
                temp_file
            ):
                os.remove(
                    temp_file
                )

            continue


        # =================================================
        # Verify all added outgroups
        # =================================================

        try:

            final_records = list(
                SeqIO.parse(
                    output_file,
                    "fasta"
                )
            )

        except Exception as e:

            print(
                f"[ERROR] Cannot read MAFFT "
                f"output: {e}"
            )

            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "INVALID_MAFFT_OUTPUT",
                str(e)
            ])

            n_mafft_failed += 1

            if os.path.exists(
                output_file
            ):
                os.remove(
                    output_file
                )

            if os.path.exists(
                temp_file
            ):
                os.remove(
                    temp_file
                )

            continue


        final_taxa = {
            record.id
            for record in final_records
        }


        missing_from_output = [
            x
            for x in [
                r.id
                for r in records_to_add
            ]
            if x not in final_taxa
        ]


        if missing_from_output:

            print(
                "[ERROR] The following outgroups "
                "are missing from MAFFT output:"
            )

            for outgroup in missing_from_output:

                print(
                    f"    {outgroup}"
                )


            summary_rows.append([
                og,
                mo_filename,
                rt_filename,
                "OUTGROUP_MISSING_FROM_OUTPUT",
                ",".join(
                    missing_from_output
                )
            ])

            n_mafft_failed += 1

            if os.path.exists(
                output_file
            ):
                os.remove(
                    output_file
                )

            if os.path.exists(
                temp_file
            ):
                os.remove(
                    temp_file
                )

            continue


        # =================================================
        # Successful
        # =================================================

        added_names = [
            r.id
            for r in records_to_add
        ]


        print(
            f"[SUCCESS] {output_filename}"
        )

        print(
            "Added outgroups: "
            + ", ".join(
                added_names
            )
        )


        summary_rows.append([
            og,
            mo_filename,
            rt_filename,
            "ADDED_AND_ALIGNED",
            (
                f"added={','.join(added_names)};"
                f"already_same={','.join(already_same)};"
                f"already_different="
                f"{','.join(already_different)}"
            )
        ])


        n_added += 1


        # -------------------------------------------------
        # Remove temporary file
        # -------------------------------------------------

        if os.path.exists(
            temp_file
        ):

            os.remove(
                temp_file
            )


# =========================================================
# STEP 6: Write summary
# =========================================================

print()
print("======================================")
print("Writing summary")
print("======================================")


with open(
    summary_file,
    "w"
) as f:

    f.write(
        "OG\tMO_file\tRT_file\tStatus\tDetails\n"
    )

    for row in summary_rows:

        f.write(
            "\t".join(
                str(x)
                for x in row
            )
            + "\n"
        )


# =========================================================
# STEP 7: Final statistics
# =========================================================

print()
print("======================================")
print("FINAL SUMMARY")
print("======================================")


print(
    f"Outgroups:                         "
    f"{','.join(outgroups)}"
)

print(
    f"RT files processed:                "
    f"{n_processed}"
)

print(
    f"RT files with outgroups added:     "
    f"{n_added}"
)

print(
    f"Outgroups already present (same):  "
    f"{n_already_same}"
)

print(
    f"Outgroups already present "
    f"(different):                      "
    f"{n_already_different}"
)

print(
    f"Missing MO:                        "
    f"{n_missing_mo}"
)

print(
    f"Missing outgroups in MO:           "
    f"{n_missing_outgroup}"
)

print(
    f"MAFFT failed:                      "
    f"{n_mafft_failed}"
)

print(
    f"Invalid/empty RT:                  "
    f"{n_invalid_rt}"
)

print()
print(
    f"Summary file: {summary_file}"
)

print()
print("Done.")
